-- FilmLab database schema and sample data
-- PostgreSQL 14+
-- Run on an empty database: psql -d <database_name> -f sql/filmlab_database.sql

\encoding UTF8
\set ON_ERROR_STOP on

BEGIN;

-- ============================================================
-- P1 - Core Domain: tài khoản, RBAC, Film Lab, dịch vụ và đơn hàng
-- P2 sử dụng và mở rộng các bảng users, film_labs, lab_services.
-- ============================================================
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    phone VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'inactive', 'suspended')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CHECK (updated_at >= created_at),
    CHECK (deleted_at IS NULL OR deleted_at >= created_at)
);

CREATE TABLE roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(50) NOT NULL UNIQUE,
    role_name VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE permissions (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR(100) NOT NULL UNIQUE,
    permission_name VARCHAR(150) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    role_id BIGINT NOT NULL REFERENCES roles(role_id) ON DELETE RESTRICT,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by BIGINT REFERENCES users(user_id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL REFERENCES roles(role_id) ON DELETE RESTRICT,
    permission_id BIGINT NOT NULL REFERENCES permissions(permission_id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE film_labs (
    lab_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    lab_name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    address TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'approved', 'suspended', 'closed')),
    approved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE TABLE lab_services (
    service_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_id BIGINT NOT NULL REFERENCES film_labs(lab_id) ON DELETE RESTRICT,
    service_code VARCHAR(50) NOT NULL,
    service_name VARCHAR(150) NOT NULL,
    description TEXT,
    base_price NUMERIC(12,2) NOT NULL CHECK (base_price >= 0),
    turnaround_hours INTEGER NOT NULL CHECK (turnaround_hours > 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (lab_id, service_code)
);

CREATE TABLE service_packages (
    package_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_id BIGINT NOT NULL REFERENCES film_labs(lab_id) ON DELETE RESTRICT,
    package_code VARCHAR(50) NOT NULL,
    package_name VARCHAR(150) NOT NULL,
    description TEXT,
    package_price NUMERIC(12,2) NOT NULL CHECK (package_price >= 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (lab_id, package_code)
);

CREATE TABLE package_services (
    package_id BIGINT NOT NULL REFERENCES service_packages(package_id) ON DELETE RESTRICT,
    service_id BIGINT NOT NULL REFERENCES lab_services(service_id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (package_id, service_id)
);

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    lab_id BIGINT NOT NULL REFERENCES film_labs(lab_id) ON DELETE RESTRICT,
    order_code VARCHAR(30) NOT NULL UNIQUE,
    status VARCHAR(30) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'confirmed', 'received', 'processing', 'scanning', 'completed', 'delivered', 'cancelled')),
    fulfillment_method VARCHAR(20) NOT NULL CHECK (fulfillment_method IN ('dropoff', 'pickup')),
    delivery_fee NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (delivery_fee >= 0),
    discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    currency_code CHAR(3) NOT NULL DEFAULT 'VND',
    special_instructions TEXT,
    placed_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE RESTRICT,
    service_id BIGINT REFERENCES lab_services(service_id) ON DELETE RESTRICT,
    package_id BIGINT REFERENCES service_packages(package_id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0),
    service_options JSONB,
    item_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((service_id IS NOT NULL) <> (package_id IS NOT NULL))
);

-- ============================================================
-- P3 - Quản lý cuộn phim, công đoạn xử lý và giao nhận
-- ============================================================
CREATE TABLE film_rolls (
    film_roll_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE RESTRICT,
    roll_code VARCHAR(50) NOT NULL,
    film_type VARCHAR(50) NOT NULL,
    frame_count INTEGER CHECK (frame_count >= 0),
    received_at TIMESTAMPTZ,
    scan_completed_at TIMESTAMPTZ,
    status VARCHAR(30) NOT NULL,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE processing_stages (
    processing_stage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_code VARCHAR(50) NOT NULL UNIQUE,
    stage_name VARCHAR(100) NOT NULL,
    stage_order INTEGER NOT NULL CHECK (stage_order > 0),
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE stage_logs (
    stage_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_roll_id BIGINT NOT NULL REFERENCES film_rolls(film_roll_id) ON DELETE RESTRICT,
    processing_stage_id BIGINT NOT NULL REFERENCES processing_stages(processing_stage_id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    operator_id BIGINT REFERENCES users(user_id) ON DELETE RESTRICT,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at)
);

CREATE TABLE order_status_history (
    order_status_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE RESTRICT,
    old_status VARCHAR(30),
    new_status VARCHAR(30) NOT NULL,
    changed_by BIGINT REFERENCES users(user_id) ON DELETE RESTRICT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pickup_delivery_requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(order_id) ON DELETE RESTRICT,
    request_type VARCHAR(20) NOT NULL CHECK (request_type IN ('pickup', 'delivery')),
    status VARCHAR(30) NOT NULL,
    pickup_address TEXT,
    delivery_address TEXT,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (completed_at IS NULL OR completed_at >= requested_at)
);

-- ============================================================
-- P4 - Kho ảnh phim số
-- ============================================================
CREATE TABLE scan_files (
    scan_file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_roll_id BIGINT NOT NULL REFERENCES film_rolls(film_roll_id) ON DELETE RESTRICT,
    storage_url TEXT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_format VARCHAR(20) NOT NULL,
    file_size BIGINT NOT NULL CHECK (file_size >= 0),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE albums (
    album_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    album_name VARCHAR(150) NOT NULL,
    description TEXT,
    visibility VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE album_photos (
    album_id BIGINT NOT NULL REFERENCES albums(album_id) ON DELETE RESTRICT,
    scan_file_id BIGINT NOT NULL REFERENCES scan_files(scan_file_id) ON DELETE RESTRICT,
    display_order INTEGER NOT NULL CHECK (display_order >= 0),
    added_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (album_id, scan_file_id)
);

CREATE TABLE tags (
    tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE photo_tags (
    scan_file_id BIGINT NOT NULL REFERENCES scan_files(scan_file_id) ON DELETE RESTRICT,
    tag_id BIGINT NOT NULL REFERENCES tags(tag_id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (scan_file_id, tag_id)
);

CREATE TABLE film_stocks (
    film_stock_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand VARCHAR(100) NOT NULL,
    stock_name VARCHAR(150) NOT NULL,
    iso INTEGER NOT NULL CHECK (iso > 0),
    film_format VARCHAR(50) NOT NULL,
    film_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE camera_models (
    camera_model_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand VARCHAR(100) NOT NULL,
    model_name VARCHAR(150) NOT NULL,
    camera_type VARCHAR(50),
    film_format VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lenses (
    lens_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand VARCHAR(100) NOT NULL,
    model_name VARCHAR(150) NOT NULL,
    focal_length VARCHAR(100),
    max_aperture VARCHAR(50),
    mount_type VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE photo_metadata (
    photo_metadata_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_file_id BIGINT NOT NULL UNIQUE REFERENCES scan_files(scan_file_id) ON DELETE RESTRICT,
    film_stock_id BIGINT REFERENCES film_stocks(film_stock_id) ON DELETE RESTRICT,
    camera_model_id BIGINT REFERENCES camera_models(camera_model_id) ON DELETE RESTRICT,
    lens_id BIGINT REFERENCES lenses(lens_id) ON DELETE RESTRICT,
    shooting_date DATE,
    scan_resolution VARCHAR(100),
    location TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- P4 - Chợ thiết bị nhiếp ảnh
-- ============================================================
CREATE TABLE product_categories (
    product_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(150) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_category_id BIGINT NOT NULL REFERENCES product_categories(product_category_id) ON DELETE RESTRICT,
    product_name VARCHAR(150) NOT NULL,
    brand VARCHAR(100),
    model_name VARCHAR(150),
    condition VARCHAR(50) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE listings (
    listing_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(product_id) ON DELETE RESTRICT,
    seller_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    title VARCHAR(200) NOT NULL,
    price NUMERIC(12,2) NOT NULL CHECK (price >= 0),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE marketplace_transactions (
    marketplace_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL UNIQUE REFERENCES listings(listing_id) ON DELETE RESTRICT,
    buyer_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    agreed_price NUMERIC(12,2) NOT NULL CHECK (agreed_price >= 0),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE seller_reviews (
    seller_review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marketplace_transaction_id BIGINT NOT NULL UNIQUE REFERENCES marketplace_transactions(marketplace_transaction_id) ON DELETE RESTRICT,
    reviewer_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    seller_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- P5 - Tri thức, cộng đồng, đánh giá Film Lab và hỗ trợ AI
-- ============================================================
CREATE TABLE article_categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE articles (
    article_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    category_id BIGINT NOT NULL REFERENCES article_categories(category_id) ON DELETE RESTRICT,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    tags VARCHAR(255),
    view_count INTEGER NOT NULL DEFAULT 0 CHECK (view_count >= 0),
    status VARCHAR(20) NOT NULL DEFAULT 'published'
        CHECK (status IN ('draft', 'published', 'archived')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lab_reviews (
    review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    lab_id BIGINT NOT NULL REFERENCES film_labs(lab_id) ON DELETE RESTRICT,
    rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE community_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    location VARCHAR(255) NOT NULL,
    event_date TIMESTAMPTZ NOT NULL,
    max_participants INTEGER CHECK (max_participants > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_interactions (
    interaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id) ON DELETE RESTRICT,
    target_type VARCHAR(50) NOT NULL CHECK (target_type IN ('article', 'film_lab', 'film_stock')),
    target_id BIGINT NOT NULL,
    interaction_type VARCHAR(20) NOT NULL CHECK (interaction_type IN ('view', 'like', 'search', 'bookmark', 'share')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ai_chat_log (
    chat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(user_id) ON DELETE SET NULL,
    user_query TEXT NOT NULL,
    bot_response TEXT NOT NULL,
    context_retrieved TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for common search and tracking flows
CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_orders_lab_status ON orders(lab_id, status);
CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_film_rolls_order ON film_rolls(order_id);
CREATE INDEX idx_stage_logs_roll ON stage_logs(film_roll_id, created_at DESC);
CREATE INDEX idx_scan_files_roll ON scan_files(film_roll_id);
CREATE INDEX idx_listings_status ON listings(status, created_at DESC);
CREATE INDEX idx_articles_category ON articles(category_id);
CREATE INDEX idx_lab_reviews_lab ON lab_reviews(lab_id, created_at DESC);
CREATE INDEX idx_interactions_target ON user_interactions(target_type, target_id);

-- ============================================================
-- Dữ liệu mẫu P1/P2: người dùng, quyền, Film Lab và đơn hàng
-- ============================================================
-- Sample users, roles and permissions
INSERT INTO users (user_id, email, password_hash, full_name, phone) VALUES
(1, 'admin@filmlab.vn', '$2b$12$sample.admin.hash', 'Quản trị hệ thống', '0901000001'),
(2, 'owner@saigonfilm.vn', '$2b$12$sample.owner.hash', 'Nguyễn Minh Lab', '0901000002'),
(3, 'an.photographer@example.com', '$2b$12$sample.customer.hash', 'Trần Hoàng An', '0901000003'),
(4, 'expert@example.com', '$2b$12$sample.expert.hash', 'Lê Thanh Hà', '0901000004'),
(5, 'seller@example.com', '$2b$12$sample.seller.hash', 'Phạm Quốc Bảo', '0901000005');

INSERT INTO roles (role_id, role_code, role_name) VALUES
(6, 'ADMIN', 'Quản trị viên'),
(7, 'LAB_OWNER', 'Chủ Film Lab'),
(8, 'PHOTOGRAPHER', 'Người chụp ảnh'),
(9, 'EXPERT', 'Chuyên gia nhiếp ảnh');

INSERT INTO permissions (permission_id, permission_code, permission_name) VALUES
(10, 'MANAGE_USERS', 'Quản lý người dùng'),
(11, 'MANAGE_LAB', 'Quản lý Film Lab'),
(12, 'CREATE_ORDER', 'Tạo đơn dịch vụ'),
(13, 'PUBLISH_ARTICLE', 'Xuất bản bài viết');

INSERT INTO user_roles (user_id, role_id, assigned_by) VALUES
(1, 6, 1),
(2, 7, 1),
(3, 8, 1),
(4, 9, 1);

INSERT INTO role_permissions (role_id, permission_id) VALUES
(6, 10),
(7, 11),
(8, 12),
(9, 13);

-- Film Lab, services and an order
INSERT INTO film_labs (lab_id, owner_id, lab_name, email, phone, address, status, approved_at) VALUES
(14, 2, 'Saigon Analog Lab', 'contact@saigonfilm.vn', '02838000001', '12 Nguyễn Huệ, Quận 1, TP.HCM', 'approved', '2026-01-05 08:00:00+07');

INSERT INTO lab_services (service_id, lab_id, service_code, service_name, base_price, turnaround_hours) VALUES
(15, 14, 'DEV-C41', 'Tráng phim màu C-41', 80000, 48),
(16, 14, 'SCAN-HI', 'Scan độ phân giải cao', 120000, 72);

INSERT INTO service_packages (package_id, lab_id, package_code, package_name, package_price) VALUES
(17, 14, 'DEV-SCAN', 'Gói tráng và scan', 180000);

INSERT INTO package_services (package_id, service_id, quantity) VALUES
(17, 15, 1),
(17, 16, 1);

INSERT INTO orders (order_id, customer_id, lab_id, order_code, status, fulfillment_method, delivery_fee, discount_amount, special_instructions, placed_at) VALUES
(18, 3, 14, 'ORD-2026-0001', 'completed', 'pickup', 30000, 10000, 'Ưu tiên màu tự nhiên', '2026-02-10 09:00:00+07');

INSERT INTO order_items (order_item_id, order_id, package_id, quantity, unit_price, service_options) VALUES
(19, 18, 17, 1, 180000, '{"scan_format":"TIFF","resolution":"4000dpi"}');

-- ============================================================
-- Dữ liệu mẫu P3/P4: xử lý phim và kho ảnh số
-- ============================================================
-- Processing lifecycle and digital archive
INSERT INTO film_rolls (film_roll_id, order_id, roll_code, film_type, frame_count, received_at, scan_completed_at, status) VALUES
(20, 18, 'ROLL-0001', 'Color Negative', 36, '2026-02-10 11:00:00+07', '2026-02-12 16:00:00+07', 'completed');

INSERT INTO processing_stages (processing_stage_id, stage_code, stage_name, stage_order) VALUES
(21, 'DEVELOP', 'Tráng phim', 1),
(22, 'SCAN', 'Scan phim', 2),
(23, 'QUALITY_CHECK', 'Kiểm tra chất lượng', 3);

INSERT INTO stage_logs (stage_log_id, film_roll_id, processing_stage_id, status, started_at, completed_at, operator_id) VALUES
(24, 20, 21, 'completed', '2026-02-11 08:00:00+07', '2026-02-11 09:00:00+07', 2),
(25, 20, 22, 'completed', '2026-02-12 13:00:00+07', '2026-02-12 15:30:00+07', 2);

INSERT INTO order_status_history (order_status_history_id, order_id, old_status, new_status, changed_by, changed_at) VALUES
(26, 18, 'processing', 'scanning', 2, '2026-02-12 13:00:00+07'),
(27, 18, 'scanning', 'completed', 2, '2026-02-12 16:00:00+07');

INSERT INTO pickup_delivery_requests (request_id, order_id, request_type, status, pickup_address, requested_at, completed_at) VALUES
(28, 18, 'pickup', 'completed', '25 Lê Lợi, Quận 1, TP.HCM', '2026-02-10 09:05:00+07', '2026-02-10 10:30:00+07');

INSERT INTO scan_files (scan_file_id, film_roll_id, storage_url, file_name, file_format, file_size, status) VALUES
(29, 20, 'https://storage.example.com/scans/roll-0001-01.tif', 'roll-0001-01.tif', 'TIFF', 52428800, 'published');

INSERT INTO albums (album_id, user_id, album_name, description, visibility) VALUES
(30, 3, 'Sài Gòn tháng Hai', 'Ảnh chụp đường phố bằng phim màu', 'private');

INSERT INTO album_photos (album_id, scan_file_id, display_order) VALUES
(30, 29, 1);

INSERT INTO tags (tag_id, tag_name) VALUES
(31, 'street'),
(32, 'saigon');

INSERT INTO photo_tags (scan_file_id, tag_id) VALUES
(29, 31),
(29, 32);

INSERT INTO film_stocks (film_stock_id, brand, stock_name, iso, film_format, film_type) VALUES
(33, 'Kodak', 'Gold 200', 200, '35mm', 'Color Negative');

INSERT INTO camera_models (camera_model_id, brand, model_name, camera_type, film_format) VALUES
(34, 'Canon', 'AE-1 Program', 'SLR', '35mm');

INSERT INTO lenses (lens_id, brand, model_name, focal_length, max_aperture, mount_type) VALUES
(35, 'Canon', 'FD 50mm', '50mm', 'f/1.8', 'Canon FD');

INSERT INTO photo_metadata (photo_metadata_id, scan_file_id, film_stock_id, camera_model_id, lens_id, shooting_date, scan_resolution, location) VALUES
(36, 29, 33, 34, 35, '2026-02-01', '4000 dpi', 'Quận 1, TP.HCM');

-- Dữ liệu mẫu P4: marketplace
INSERT INTO product_categories (product_category_id, category_name, description) VALUES
(37, 'Máy ảnh phim', 'Máy ảnh sử dụng phim analog');

INSERT INTO products (product_id, product_category_id, product_name, brand, model_name, condition, description) VALUES
(38, 37, 'Canon AE-1 Program', 'Canon', 'AE-1 Program', 'used_good', 'Máy hoạt động tốt, đo sáng chính xác');

INSERT INTO listings (listing_id, product_id, seller_id, title, price, status) VALUES
(39, 38, 5, 'Canon AE-1 Program kèm lens 50mm', 4500000, 'sold');

INSERT INTO marketplace_transactions (marketplace_transaction_id, listing_id, buyer_id, agreed_price, status) VALUES
(40, 39, 3, 4300000, 'completed');

INSERT INTO seller_reviews (seller_review_id, marketplace_transaction_id, reviewer_id, seller_id, rating, comment) VALUES
(41, 40, 3, 5, 5, 'Máy đúng mô tả, đóng gói cẩn thận.');

-- Dữ liệu mẫu P5: tri thức, cộng đồng và AI
INSERT INTO article_categories (category_id, category_name, description) VALUES
(42, 'Kỹ thuật chụp phim', 'Kiến thức và kinh nghiệm chụp ảnh phim');

INSERT INTO articles (article_id, author_id, category_id, title, content, tags, view_count) VALUES
(43, 4, 42, 'Cách chọn phim cho người mới', 'Nên bắt đầu với phim ISO 200 hoặc 400 tùy điều kiện ánh sáng.', 'film,iso,beginner', 128);

INSERT INTO lab_reviews (review_id, user_id, lab_id, rating, comment) VALUES
(44, 3, 14, 5, 'Ảnh scan đẹp, thời gian xử lý đúng hẹn.');

INSERT INTO community_events (event_id, host_id, title, description, location, event_date, max_participants) VALUES
(45, 4, 'Photowalk Sài Gòn cuối tuần', 'Chụp ảnh phim quanh khu trung tâm.', 'Bưu điện Thành phố, TP.HCM', '2026-10-18 07:30:00+07', 30);

INSERT INTO user_interactions (interaction_id, user_id, target_type, target_id, interaction_type) VALUES
(46, 3, 'article', 43, 'bookmark'),
(47, 3, 'film_lab', 14, 'view');

INSERT INTO ai_chat_log (chat_id, user_id, user_query, bot_response, context_retrieved) VALUES
(48, 3, 'Nên dùng phim nào để chụp đường phố ban ngày?', 'Bạn có thể bắt đầu với Kodak Gold 200 hoặc phim ISO 400 nếu ánh sáng thay đổi nhiều.', 'Bài viết: Cách chọn phim cho người mới');

-- ============================================================
-- Bộ dữ liệu mẫu bổ sung để thử tìm kiếm, thống kê và báo cáo
-- ============================================================
INSERT INTO users (user_id, email, password_hash, full_name, phone) VALUES
(49, 'linh.photographer@example.com', '$2b$12$sample.linh.hash', 'Võ Ngọc Linh', '0901000006'),
(50, 'owner@hanoianalog.vn', '$2b$12$sample.hanoi.owner.hash', 'Đỗ Anh Tuấn', '0901000007');

INSERT INTO user_roles (user_id, role_id, assigned_by) VALUES
(49, 8, 1),
(50, 7, 1);

INSERT INTO film_labs (lab_id, owner_id, lab_name, email, phone, address, status, approved_at) VALUES
(51, 50, 'Hanoi Analog Lab', 'contact@hanoianalog.vn', '02438000002', '25 Tràng Tiền, Hoàn Kiếm, Hà Nội', 'approved', '2026-03-01 09:00:00+07');

INSERT INTO lab_services (service_id, lab_id, service_code, service_name, base_price, turnaround_hours) VALUES
(52, 51, 'DEV-BW', 'Tráng phim đen trắng', 100000, 72),
(53, 51, 'SCAN-STD', 'Scan tiêu chuẩn', 70000, 48);

INSERT INTO service_packages (package_id, lab_id, package_code, package_name, package_price) VALUES
(54, 51, 'BW-SCAN', 'Gói tráng phim đen trắng và scan', 160000);

INSERT INTO package_services (package_id, service_id, quantity) VALUES
(54, 52, 1),
(54, 53, 1);

INSERT INTO orders (order_id, customer_id, lab_id, order_code, status, fulfillment_method, delivery_fee, discount_amount, special_instructions, placed_at) VALUES
(55, 49, 51, 'ORD-2026-0002', 'processing', 'dropoff', 0, 0, 'Giữ lại viền phim khi scan', '2026-04-05 14:00:00+07');

INSERT INTO order_items (order_item_id, order_id, package_id, quantity, unit_price, service_options, item_note) VALUES
(56, 55, 54, 2, 160000, '{"scan_format":"JPEG","include_border":true}', 'Hai cuộn phim đen trắng');

INSERT INTO film_rolls (film_roll_id, order_id, roll_code, film_type, frame_count, received_at, status, note) VALUES
(57, 55, 'ROLL-0002', 'Black and White', 36, '2026-04-05 15:00:00+07', 'processing', 'Kentmere 400'),
(58, 55, 'ROLL-0003', 'Black and White', 24, '2026-04-05 15:00:00+07', 'received', 'Ilford HP5 Plus');

INSERT INTO stage_logs (stage_log_id, film_roll_id, processing_stage_id, status, started_at, operator_id, note) VALUES
(59, 57, 21, 'processing', '2026-04-06 08:00:00+07', 50, 'Đang tráng bằng hóa chất mới');

INSERT INTO order_status_history (order_status_history_id, order_id, old_status, new_status, changed_by, changed_at, note) VALUES
(60, 55, 'received', 'processing', 50, '2026-04-06 08:00:00+07', 'Bắt đầu xử lý cuộn đầu tiên');

INSERT INTO scan_files (scan_file_id, film_roll_id, storage_url, file_name, file_format, file_size, status) VALUES
(61, 57, 'https://storage.example.com/previews/roll-0002-contact-sheet.jpg', 'roll-0002-contact-sheet.jpg', 'JPEG', 3145728, 'preview');

INSERT INTO albums (album_id, user_id, album_name, description, visibility) VALUES
(62, 49, 'Hà Nội đen trắng', 'Bộ ảnh đời sống tại khu phố cổ', 'public');

INSERT INTO album_photos (album_id, scan_file_id, display_order) VALUES
(62, 61, 1);

INSERT INTO photo_tags (scan_file_id, tag_id) VALUES
(61, 31);

INSERT INTO film_stocks (film_stock_id, brand, stock_name, iso, film_format, film_type) VALUES
(63, 'Ilford', 'HP5 Plus', 400, '35mm', 'Black and White');

INSERT INTO photo_metadata (photo_metadata_id, scan_file_id, film_stock_id, shooting_date, scan_resolution, location, notes) VALUES
(64, 61, 63, '2026-03-28', '2400 dpi', 'Hoàn Kiếm, Hà Nội', 'Contact sheet xem trước');

INSERT INTO products (product_id, product_category_id, product_name, brand, model_name, condition, description) VALUES
(65, 37, 'Nikon FM2', 'Nikon', 'FM2', 'used_very_good', 'Thân máy sạch, màn trập hoạt động ổn định');

INSERT INTO listings (listing_id, product_id, seller_id, title, price, status) VALUES
(66, 65, 50, 'Nikon FM2 màu bạc', 7200000, 'active');

INSERT INTO articles (article_id, author_id, category_id, title, content, tags, view_count) VALUES
(67, 4, 42, 'Kinh nghiệm chụp phim đen trắng', 'Đo sáng vào vùng trung gian và chú ý độ tương phản của cảnh.', 'black-white,metering,contrast', 76);

INSERT INTO lab_reviews (review_id, user_id, lab_id, rating, comment) VALUES
(68, 49, 51, 4, 'Nhân viên tư vấn kỹ, thời gian xử lý hợp lý.');

INSERT INTO community_events (event_id, host_id, title, description, location, event_date, max_participants) VALUES
(69, 50, 'Workshop tráng phim đen trắng', 'Thực hành tráng phim tại phòng tối.', 'Hanoi Analog Lab', '2026-11-08 09:00:00+07', 12);

INSERT INTO user_interactions (interaction_id, user_id, target_type, target_id, interaction_type) VALUES
(70, 49, 'article', 67, 'like'),
(71, 49, 'film_stock', 63, 'bookmark');

INSERT INTO ai_chat_log (chat_id, user_id, user_query, bot_response, context_retrieved) VALUES
(72, 49, 'Phim đen trắng ISO 400 phù hợp chụp gì?', 'Phim ISO 400 phù hợp chụp đường phố, trong nhà và điều kiện ánh sáng thay đổi.', 'Film stock: Ilford HP5 Plus; bài viết về phim đen trắng');

-- Dữ liệu sinh thêm: 20 khách hàng, 10 đơn hàng và 10 cuộn phim
INSERT INTO users (user_id, email, password_hash, full_name, phone)
SELECT 100 + n,
       'photographer' || n || '@example.com',
       '$2b$12$sample.generated.hash',
       'Khách hàng mẫu ' || n,
       '0912' || LPAD(n::TEXT, 6, '0')
FROM generate_series(1, 20) AS n;

INSERT INTO user_roles (user_id, role_id, assigned_by)
SELECT 100 + n, 8, 1
FROM generate_series(1, 20) AS n;

INSERT INTO orders (
    order_id, customer_id, lab_id, order_code, status,
    fulfillment_method, delivery_fee, discount_amount, placed_at
)
SELECT 200 + n,
       100 + n,
       CASE WHEN n % 2 = 0 THEN 14 ELSE 51 END,
       'ORD-2026-' || LPAD((n + 2)::TEXT, 4, '0'),
       CASE WHEN n % 3 = 0 THEN 'completed' ELSE 'confirmed' END,
       CASE WHEN n % 2 = 0 THEN 'pickup' ELSE 'dropoff' END,
       CASE WHEN n % 2 = 0 THEN 30000 ELSE 0 END,
       CASE WHEN n % 5 = 0 THEN 10000 ELSE 0 END,
       TIMESTAMPTZ '2026-05-01 08:00:00+07' + (n || ' days')::INTERVAL
FROM generate_series(1, 10) AS n;

INSERT INTO order_items (
    order_item_id, order_id, service_id, quantity,
    unit_price, service_options, item_note
)
SELECT 300 + n,
       200 + n,
       CASE WHEN n % 2 = 0 THEN 15 ELSE 52 END,
       1 + (n % 2),
       CASE WHEN n % 2 = 0 THEN 80000 ELSE 100000 END,
       jsonb_build_object(
           'scan_format', CASE WHEN n % 2 = 0 THEN 'TIFF' ELSE 'JPEG' END,
           'sample_number', n
       ),
       'Hạng mục dữ liệu mẫu số ' || n
FROM generate_series(1, 10) AS n;

INSERT INTO film_rolls (
    film_roll_id, order_id, roll_code, film_type,
    frame_count, received_at, status, note
)
SELECT 400 + n,
       200 + n,
       'ROLL-' || LPAD((n + 3)::TEXT, 4, '0'),
       CASE WHEN n % 2 = 0 THEN 'Color Negative' ELSE 'Black and White' END,
       CASE WHEN n % 3 = 0 THEN 24 ELSE 36 END,
       TIMESTAMPTZ '2026-05-02 09:00:00+07' + (n || ' days')::INTERVAL,
       CASE WHEN n % 3 = 0 THEN 'completed' ELSE 'received' END,
       'Cuộn phim dữ liệu mẫu số ' || n
FROM generate_series(1, 10) AS n;

-- Đồng bộ sequence sau khi chèn ID mẫu tường minh.
DO $$
DECLARE
    identity_column RECORD;
    sequence_name TEXT;
BEGIN
    FOR identity_column IN
        SELECT table_schema, table_name, column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND is_identity = 'YES'
    LOOP
        sequence_name := pg_get_serial_sequence(
            format('%I.%I', identity_column.table_schema, identity_column.table_name),
            identity_column.column_name
        );
        EXECUTE format(
            'SELECT setval(%L, COALESCE(MAX(%I), 0) + 1, false) FROM %I.%I',
            sequence_name,
            identity_column.column_name,
            identity_column.table_schema,
            identity_column.table_name
        );
    END LOOP;
END $$;

COMMIT;

-- Example: calculate order subtotal and total from snapshot prices
SELECT o.order_code,
       SUM(oi.quantity * oi.unit_price) AS subtotal,
       SUM(oi.quantity * oi.unit_price) + o.delivery_fee - o.discount_amount AS total_amount
FROM orders o
JOIN order_items oi ON oi.order_id = o.order_id
GROUP BY o.order_id, o.order_code, o.delivery_fee, o.discount_amount;
